version: '3.2'

services:
  web:
    build: 
      context: ./
      dockerfile: Dockerfile
    container_name: php-apache
    restart: always
    depends_on:
      - db
    volumes:
      - ./docker/www:/var/www/html/
    ports:
      - 8000:80

  db:
    container_name: mysql
    image: mysql:8.0.26
    restart: always
    command:  --default-authentication-plugin=mysql_native_password
    volumes:
      - ./docker/db:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: akashdeep
      MYSQL_PASSWORD: akpass
